"""GeneratedClass model — an ObjectScript .cls file generated by the CodeGen agent"""

import uuid
from datetime import datetime

from sqlalchemy import ForeignKey, Integer, String, Text, text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.models.base import Base


class GeneratedClass(Base):
    __tablename__ = "generated_classes"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    mapping_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("mappings.id", ondelete="CASCADE"),
        index=True,
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("projects.id", ondelete="CASCADE"),
        index=True,
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id"),
        index=True,
    )
    class_name: Mapped[str] = mapped_column(String(500), nullable=False)
    s3_key: Mapped[str] = mapped_column(Text, nullable=False)
    version: Mapped[int] = mapped_column(Integer, server_default=text("1"))
    content_hash: Mapped[str | None] = mapped_column(String(64), nullable=True)
    generation_model: Mapped[str | None] = mapped_column(String(100), nullable=True)
    generation_prompt_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    generation_completion_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    validation_status: Mapped[str | None] = mapped_column(String(50), nullable=True)
    validation_issues: Mapped[list] = mapped_column(
        JSONB, server_default=text("'[]'::jsonb")
    )
    deploy_status: Mapped[dict] = mapped_column(
        JSONB, server_default=text("'{}'::jsonb")
    )
    created_at: Mapped[datetime] = mapped_column(server_default=text("NOW()"))

    mapping = relationship("Mapping", back_populates="generated_classes")
    project = relationship("Project")
