"""
Seed script: Creates a full UC CHRISTUS mock project with realistic data.
Populates all tables through the pipeline: register → project → components → mappings → generated → tests

Usage: cd apps/api && source .venv/bin/activate && PYTHONPATH=. python scripts/seed_mock_data.py
"""

import asyncio
import hashlib
import uuid
from datetime import datetime, timezone

from sqlalchemy import text

from src.config import settings
from src.db import SyncSession
from src.models.audit_log import AuditLog
from src.models.generated_class import GeneratedClass
from src.models.iris_connection import IRISConnection
from src.models.mapping import Mapping
from src.models.project import Project
from src.models.source_component import SourceComponent
from src.models.tenant import Tenant
from src.models.test_case import TestCase
from src.models.test_result import TestResult
from src.models.user import User
from src.utils.security import get_password_hash

# ============================================================
# Mock ObjectScript code samples
# ============================================================
MOCK_BS_CODE = """/// ADT Inbound Service - Receives HL7 ADT messages via MLLP
/// Generated by HealthBridge AI
Class HB.BS.ADTInbound Extends EnsLib.HL7.Service.TCPService
{

Parameter ADAPTER = "EnsLib.HL7.Adapter.TCPInboundAdapter";
Parameter SETTINGS = "TargetConfigNames:Basic";
Property TargetConfigNames As %String(MAXLEN = 1000) [ InitialExpression = "HB.BP.ADTRouter" ];

Method OnProcessInput(pInput As EnsLib.HL7.Message, pOutput As EnsLib.HL7.Message) As %Status
{
    Set tSC = $$$OK
    Set tOrigNS = $NAMESPACE
    Try {
        $$$LOGINFO("ADTInbound: Received message type " _ pInput.GetValueAt("MSH:9.1") _ "^" _ pInput.GetValueAt("MSH:9.2"))
        Set tSC = ..SendRequestAsync("HB.BP.ADTRouter", pInput)
    }
    Catch ex {
        Set $NAMESPACE = tOrigNS
        Set tSC = ex.AsStatus()
        $$$LOGERROR("ADTInbound Error: " _ $System.Status.GetErrorText(tSC))
    }
    Quit tSC
}

}
"""

MOCK_BP_CODE = """/// ADT Router - Routes ADT messages based on message type
/// Generated by HealthBridge AI
Class HB.BP.ADTRouter Extends Ens.BusinessProcess
{

Property TargetADT As %String(MAXLEN = 500) [ InitialExpression = "HB.BO.ADTOutbound" ];
Property TargetORM As %String(MAXLEN = 500) [ InitialExpression = "HB.BO.ORMOutbound" ];
Parameter SETTINGS = "TargetADT:Basic,TargetORM:Basic";

Method OnRequest(pRequest As EnsLib.HL7.Message, Output pResponse As EnsLib.HL7.Message) As %Status
{
    Set tSC = $$$OK
    Set tOrigNS = $NAMESPACE
    Try {
        Set tMsgType = pRequest.GetValueAt("MSH:9.1")
        $$$LOGINFO("ADTRouter: Routing message type " _ tMsgType)

        If (tMsgType = "ADT") {
            Set tSC = ..SendRequestAsync(..TargetADT, pRequest)
        }
        ElseIf (tMsgType = "ORM") {
            Set tSC = ..SendRequestAsync(..TargetORM, pRequest)
        }
        Else {
            $$$LOGINFO("ADTRouter: Unknown message type " _ tMsgType _ ", dropping")
        }
    }
    Catch ex {
        Set $NAMESPACE = tOrigNS
        Set tSC = ex.AsStatus()
        $$$LOGERROR("ADTRouter Error: " _ $System.Status.GetErrorText(tSC))
    }
    Quit tSC
}

}
"""

MOCK_BO_CODE = """/// ADT Outbound Operation - Sends HL7 messages to downstream system via MLLP
/// Generated by HealthBridge AI
Class HB.BO.ADTOutbound Extends EnsLib.HL7.Operation.TCPOperation
{

Parameter ADAPTER = "EnsLib.HL7.Adapter.TCPOutboundAdapter";
Parameter SETTINGS = "IPAddress:Basic,Port:Basic";
Property IPAddress As %String [ InitialExpression = "192.168.1.100" ];
Property Port As %Integer [ InitialExpression = 2575 ];

Method OnMessage(pRequest As EnsLib.HL7.Message, Output pResponse As EnsLib.HL7.Message) As %Status
{
    Set tSC = $$$OK
    Set tOrigNS = $NAMESPACE
    Try {
        $$$LOGINFO("ADTOutbound: Sending message to " _ ..IPAddress _ ":" _ ..Port)
        Set tSC = ..Adapter.SendMessageAndReceiveResponse(pRequest, .pResponse)
        If $$$ISOK(tSC) {
            $$$LOGINFO("ADTOutbound: ACK received")
        }
    }
    Catch ex {
        Set $NAMESPACE = tOrigNS
        Set tSC = ex.AsStatus()
        $$$LOGERROR("ADTOutbound Error: " _ $System.Status.GetErrorText(tSC))
    }
    Quit tSC
}

}
"""

MOCK_BO_SOAP_CODE = """/// SOAP Outbound - Calls external SOAP service for patient validation
/// Generated by HealthBridge AI
Class HB.BO.PatientValidation Extends Ens.BusinessOperation
{

Property SOAPEndpoint As %String(MAXLEN = 500);
Property SOAPAction As %String(MAXLEN = 500);
Property BasicAuthB64 As %String(MAXLEN = 500);
Parameter SETTINGS = "SOAPEndpoint:Basic,SOAPAction:Basic,BasicAuthB64:Basic";

Method OnMessage(pRequest As HB.MSG.ValidationRequest, Output pResponse As HB.MSG.ValidationResponse) As %Status
{
    Set tSC = $$$OK
    Set tOrigNS = $NAMESPACE
    Try {
        $$$LOGINFO("PatientValidation: Calling SOAP endpoint")
        Set tHttpReq = ##class(%Net.HttpRequest).%New()
        Set tHttpReq.ContentType = "text/xml; charset=UTF-8"
        Do tHttpReq.SetHeader("SOAPAction", ..SOAPAction)
        Do tHttpReq.SetHeader("Authorization", "Basic " _ ..BasicAuthB64)
        Do tHttpReq.EntityBody.Write(pRequest.SOAPBody)
        Set tSC = tHttpReq.Post(..SOAPEndpoint)
    }
    Catch ex {
        Set $NAMESPACE = tOrigNS
        Set tSC = ex.AsStatus()
        $$$LOGERROR("PatientValidation Error: " _ $System.Status.GetErrorText(tSC))
    }
    Quit tSC
}

}
"""

# ============================================================
# Mock HL7 messages for testing
# ============================================================
MOCK_ADT_A01 = "MSH|^~\\&|MIRTH|UCCHRISTUS|IRIS|HB|20260330120000||ADT^A01|MSG001|P|2.5\rEVN|A01|20260330120000\rPID|||12345^^^UCCHRISTUS||PEREZ^JUAN^CARLOS||19800115|M|||AV PROVIDENCIA 1234^^SANTIAGO^^7500000^CL\rPV1||I|UCI^301^A|R|||DR001^MARTINEZ^LUIS|||SUR|||||||DR001|I|V001|||||||||||||||||||HB|||||20260330120000"

MOCK_ADT_A08 = "MSH|^~\\&|MIRTH|UCCHRISTUS|IRIS|HB|20260330130000||ADT^A08|MSG002|P|2.5\rEVN|A08|20260330130000\rPID|||12345^^^UCCHRISTUS||PEREZ^JUAN^CARLOS||19800115|M|||AV PROVIDENCIA 5678^^SANTIAGO^^7500000^CL\rPV1||I|UCI^301^A|R|||DR001^MARTINEZ^LUIS|||SUR|||||||DR001|I|V001"

MOCK_ORM_O01 = "MSH|^~\\&|MIRTH|UCCHRISTUS|IRIS|HB|20260330140000||ORM^O01|MSG003|P|2.5\rPID|||12345^^^UCCHRISTUS||PEREZ^JUAN^CARLOS||19800115|M\rPV1||I|UCI^301^A\rORC|NW|ORD001|||||^^^20260330140000\rOBR|1|ORD001||85025^CBC^L|||20260330140000"


def seed():
    print("Seeding UC CHRISTUS mock data...")

    with SyncSession() as session:
        # Clean existing data
        for table in ["audit_logs", "test_results", "test_cases", "generated_classes",
                      "mappings", "source_components", "iris_connections", "projects", "users", "tenants"]:
            session.execute(text(f'TRUNCATE TABLE "{table}" CASCADE'))
        session.commit()
        print("  Cleaned existing data")

        # 1. Tenant
        tenant = Tenant(name="UC CHRISTUS Chile", slug="uc-christus")
        session.add(tenant)
        session.flush()
        print(f"  Tenant: {tenant.name} ({tenant.id})")

        # 2. Users
        admin = User(
            tenant_id=tenant.id,
            email="admin@ucchristus.cl",
            password_hash=get_password_hash("admin123"),
            role="admin",
        )
        dev = User(
            tenant_id=tenant.id,
            email="dev@ucchristus.cl",
            password_hash=get_password_hash("dev123"),
            role="member",
        )
        session.add_all([admin, dev])
        session.flush()
        print(f"  Users: admin@ucchristus.cl / admin123, dev@ucchristus.cl / dev123")

        # 3. Project
        project = Project(
            tenant_id=tenant.id,
            name="UC CHRISTUS - Migración HL7 Integraciones",
            description="Migración de 30+ flujos HL7 desde Mirth Connect y Oracle SOA hacia InterSystems IRIS HealthConnect. Incluye ADT, ORM, ORU, SIU y mensajería SOAP.",
            source_platform="mirth_connect",
            source_platforms=["mirth_connect", "oracle_soa"],
            status="analyzed",
            metadata_={},
            created_by=admin.id,
        )
        session.add(project)
        session.flush()
        print(f"  Project: {project.name} ({project.id})")

        # 4. Source Components
        components_data = [
            {
                "name": "ADT_Inbound_Channel",
                "component_type": "mirth_channel",
                "complexity": "medium",
                "analysis_result": {
                    "component_name": "ADT_Inbound_Channel",
                    "type": "mirth_channel",
                    "description": "Receives ADT messages (A01, A02, A03, A08, A28, A31) via MLLP on port 2575. Routes to IRIS based on message type.",
                    "complexity": "medium",
                    "exposed_services": [
                        {"name": "MLLP_Listener", "type": "TCP", "port": 2575, "protocol": "MLLP"}
                    ],
                    "external_references": [
                        {"name": "IRIS_TrackCare", "url": "iris-prod:2575", "type": "MLLP"}
                    ],
                    "hl7_messages": [
                        {"type": "ADT^A01", "direction": "inbound", "version": "2.5"},
                        {"type": "ADT^A08", "direction": "inbound", "version": "2.5"},
                        {"type": "ADT^A28", "direction": "inbound", "version": "2.5"},
                    ],
                    "proposed_iris_mapping": {
                        "BS": [{"class_name": "HB.BS.ADTInbound", "extends": "EnsLib.HL7.Service.TCPService"}],
                        "BP": [{"class_name": "HB.BP.ADTRouter", "extends": "Ens.BusinessProcess"}],
                        "BO": [{"class_name": "HB.BO.ADTOutbound", "extends": "EnsLib.HL7.Operation.TCPOperation"}],
                        "DTL": [],
                        "MSG": [],
                    },
                },
                "exposed_services": [{"name": "MLLP_Listener", "type": "TCP", "port": 2575, "protocol": "MLLP"}],
                "external_references": [{"name": "IRIS_TrackCare", "url": "iris-prod:2575", "type": "MLLP"}],
                "hl7_messages": [
                    {"type": "ADT^A01", "direction": "inbound", "version": "2.5"},
                    {"type": "ADT^A08", "direction": "inbound", "version": "2.5"},
                ],
            },
            {
                "name": "ORM_SOA_Composite",
                "component_type": "soa_composite",
                "complexity": "high",
                "analysis_result": {
                    "component_name": "ORM_SOA_Composite",
                    "type": "soa_composite",
                    "description": "Oracle SOA composite that processes ORM^O01 lab orders. Includes BPEL process for order validation and SOAP call to external lab system.",
                    "complexity": "high",
                    "exposed_services": [
                        {"name": "LabOrderService", "type": "SOAP", "port": 8080, "protocol": "HTTP"}
                    ],
                    "external_references": [
                        {"name": "ExternalLabSystem", "url": "https://lab.external.cl/api/orders", "type": "REST"},
                        {"name": "PatientValidation", "url": "https://sap-pi.ucchristus.cl/validate", "type": "SOAP"},
                    ],
                    "hl7_messages": [
                        {"type": "ORM^O01", "direction": "inbound", "version": "2.5"},
                    ],
                    "proposed_iris_mapping": {
                        "BS": [{"class_name": "HB.BS.LabOrderService", "extends": "EnsLib.HTTP.Service"}],
                        "BP": [{"class_name": "HB.BP.LabOrderProcessor", "extends": "Ens.BusinessProcess"}],
                        "BO": [
                            {"class_name": "HB.BO.ExternalLabClient", "extends": "Ens.BusinessOperation"},
                            {"class_name": "HB.BO.PatientValidation", "extends": "Ens.BusinessOperation"},
                        ],
                        "DTL": [{"class_name": "HB.DTL.ORMTransform", "extends": "Ens.DataTransformDTL"}],
                        "MSG": [
                            {"class_name": "HB.MSG.ValidationRequest", "extends": "Ens.Request"},
                            {"class_name": "HB.MSG.ValidationResponse", "extends": "Ens.Response"},
                        ],
                    },
                },
                "exposed_services": [{"name": "LabOrderService", "type": "SOAP", "port": 8080, "protocol": "HTTP"}],
                "external_references": [
                    {"name": "ExternalLabSystem", "url": "https://lab.external.cl/api/orders", "type": "REST"},
                    {"name": "PatientValidation", "url": "https://sap-pi.ucchristus.cl/validate", "type": "SOAP"},
                ],
                "hl7_messages": [{"type": "ORM^O01", "direction": "inbound", "version": "2.5"}],
            },
        ]

        components = []
        for cd in components_data:
            comp = SourceComponent(
                project_id=project.id, tenant_id=tenant.id,
                name=cd["name"], component_type=cd["component_type"],
                complexity=cd["complexity"], status="analyzed",
                analysis_result=cd["analysis_result"],
                exposed_services=cd["exposed_services"],
                external_references=cd["external_references"],
                hl7_messages=cd["hl7_messages"],
            )
            session.add(comp)
            components.append(comp)
        session.flush()
        print(f"  Components: {len(components)} created")

        # 5. Mappings (from proposed_iris_mapping)
        mappings_data = [
            (components[0], "HB.BS.ADTInbound", "BusinessService", "EnsLib.HL7.Service.TCPService", "BS"),
            (components[0], "HB.BP.ADTRouter", "BusinessProcess", "Ens.BusinessProcess", "BP"),
            (components[0], "HB.BO.ADTOutbound", "BusinessOperation", "EnsLib.HL7.Operation.TCPOperation", "BO"),
            (components[1], "HB.BS.LabOrderService", "BusinessService", "EnsLib.HTTP.Service", "BS"),
            (components[1], "HB.BP.LabOrderProcessor", "BusinessProcess", "Ens.BusinessProcess", "BP"),
            (components[1], "HB.BO.ExternalLabClient", "BusinessOperation", "Ens.BusinessOperation", "BO"),
            (components[1], "HB.BO.PatientValidation", "BusinessOperation", "Ens.BusinessOperation", "BO"),
            (components[1], "HB.DTL.ORMTransform", "DTL", "Ens.DataTransformDTL", "DTL"),
            (components[1], "HB.MSG.ValidationRequest", "Message", "Ens.Request", "MSG"),
            (components[1], "HB.MSG.ValidationResponse", "Message", "Ens.Response", "MSG"),
        ]

        mappings = []
        for comp, class_name, target_type, extends, layer in mappings_data:
            m = Mapping(
                project_id=project.id, tenant_id=tenant.id,
                source_component_id=comp.id,
                target_class_name=class_name,
                target_type=target_type, target_extends=extends,
                iris_layer=layer, auto_generated=True,
                confirmed_by=admin.id,
            )
            session.add(m)
            mappings.append(m)
        session.flush()
        print(f"  Mappings: {len(mappings)} created (all confirmed)")

        # 6. Generated Classes
        code_map = {
            "HB.BS.ADTInbound": (MOCK_BS_CODE, "passed"),
            "HB.BP.ADTRouter": (MOCK_BP_CODE, "passed"),
            "HB.BO.ADTOutbound": (MOCK_BO_CODE, "passed"),
            "HB.BO.PatientValidation": (MOCK_BO_SOAP_CODE, "passed"),
        }

        from src.services.storage.local import LocalStorageService
        storage = LocalStorageService()

        generated = []
        for m in mappings:
            code, status = code_map.get(m.target_class_name, ("// Placeholder class\n", "passed"))
            s3_key = f"{tenant.id}/{project.id}/generated/{m.target_class_name.replace('.', '/')}.cls"

            # Store code in local storage
            import asyncio
            asyncio.run(storage.put_file(s3_key, code.encode("utf-8"), "text/plain"))

            gc = GeneratedClass(
                mapping_id=m.id, project_id=project.id, tenant_id=tenant.id,
                class_name=m.target_class_name, s3_key=s3_key,
                version=1, content_hash=hashlib.sha256(code.encode()).hexdigest(),
                generation_model="anthropic.claude-sonnet-4-6",
                generation_prompt_tokens=2500, generation_completion_tokens=800,
                validation_status=status,
                validation_issues=[],
                deploy_status={"status": "deployed", "timestamp": "2026-03-30T12:00:00Z", "iris_server": "DEV", "namespace": "HB"},
            )
            session.add(gc)
            generated.append(gc)
        session.flush()
        print(f"  Generated classes: {len(generated)} (all validated + deployed)")

        # 7. IRIS Connection
        iris_conn = IRISConnection(
            tenant_id=tenant.id,
            name="IRIS DEV - UC CHRISTUS",
            base_url="http://iris-dev.ucchristus.cl",
            namespace="HB",
            credentials={"username": "SuperUser", "password": "SYS"},
            ssl_verify=False,
            environment="dev",
            is_active=True,
        )
        session.add(iris_conn)
        session.flush()
        print(f"  IRIS Connection: {iris_conn.name}")

        # 8. Test Cases
        test_cases_data = [
            ("ADT A01 - Admisión paciente", "mllp", 2575, MOCK_ADT_A01, "ADT^A01", "AA"),
            ("ADT A08 - Actualización paciente", "mllp", 2575, MOCK_ADT_A08, "ADT^A08", "AA"),
            ("ORM O01 - Orden laboratorio", "mllp", 2575, MOCK_ORM_O01, "ORM^O01", "AA"),
        ]

        test_cases = []
        for name, protocol, port, msg, msg_type, expected in test_cases_data:
            tc = TestCase(
                project_id=project.id, tenant_id=tenant.id,
                name=name, protocol=protocol,
                target_host="iris-dev.ucchristus.cl", target_port=port,
                message_content=msg, expected_response=expected,
                hl7_message_type=msg_type,
                tags=["mock", "uc-christus"],
                created_by=admin.id,
            )
            session.add(tc)
            test_cases.append(tc)
        session.flush()
        print(f"  Test cases: {len(test_cases)}")

        # 9. Mock Test Results (simulated)
        results_data = [
            ("pass", "AA", 45, "MSH|^~\\&|IRIS|HB|MIRTH|UCCHRISTUS|20260330||ACK|ACK001|P|2.5\rMSA|AA|MSG001"),
            ("pass", "AA", 52, "MSH|^~\\&|IRIS|HB|MIRTH|UCCHRISTUS|20260330||ACK|ACK002|P|2.5\rMSA|AA|MSG002"),
            ("pass", "AA", 128, "MSH|^~\\&|IRIS|HB|MIRTH|UCCHRISTUS|20260330||ACK|ACK003|P|2.5\rMSA|AA|MSG003"),
        ]

        for i, (status, ack, time_ms, response) in enumerate(results_data):
            tr = TestResult(
                test_case_id=test_cases[i].id,
                iris_connection_id=iris_conn.id,
                tenant_id=tenant.id,
                status=status, ack_code=ack,
                response_time_ms=time_ms,
                response_content=response,
                executed_by=admin.id,
            )
            session.add(tr)
        session.flush()
        print(f"  Test results: {len(results_data)} (all passed)")

        # 10. Deploy history
        project.status = "deployed"
        project.metadata_ = {
            "deploy_history": [
                {
                    "deployed_at": "2026-03-30T12:00:00Z",
                    "iris_connection_name": "IRIS DEV - UC CHRISTUS",
                    "namespace": "HB",
                    "total_classes": len(generated),
                    "successful": len(generated),
                    "failed": 0,
                    "status": "success",
                },
            ],
        }

        # 11. Audit logs
        audit_entries = [
            ("create", "project", project.id, {"name": project.name}),
            ("analyze", "project", project.id, {"components": len(components)}),
            ("auto_generate", "mapping", project.id, {"mappings": len(mappings)}),
            ("generate", "project", project.id, {"classes": len(generated)}),
            ("deploy", "project", project.id, {"target": "IRIS DEV", "classes": len(generated)}),
            ("execute_tests", "project", project.id, {"tests": len(test_cases), "passed": 3}),
        ]

        for action, resource_type, resource_id, details in audit_entries:
            al = AuditLog(
                tenant_id=tenant.id, user_id=admin.id,
                action=action, resource_type=resource_type,
                resource_id=resource_id, details=details,
                ip_address="192.168.1.50",
            )
            session.add(al)

        session.commit()
        print(f"  Audit logs: {len(audit_entries)}")

        print("\n=== SEED COMPLETE ===")
        print(f"Login: admin@ucchristus.cl / admin123")
        print(f"Project: {project.name}")
        print(f"  - 2 source components (Mirth + SOA)")
        print(f"  - 10 mappings (all confirmed)")
        print(f"  - {len(generated)} generated classes (deployed)")
        print(f"  - 3 test cases (all passed)")
        print(f"  - 1 IRIS connection (DEV)")
        print(f"  - 6 audit log entries")


if __name__ == "__main__":
    seed()
